channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.8
  - maturin
  - nox
  - mypy
  - ruff
  - Flake8-pyproject
  - flake8-bugbear
  - flake8-pyi
  - black
  - isort
  - pytest
  - pytest-cov
  - hypothesis
  - pip
  - sphinx
  - pydata-sphinx-theme
  - sphinx-copybutton
  - myst-parser
  - pip:
      - sphinx-autoapi

category: dev
