name: argus
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.8
  - maturin
  - nox
  - mypy
  - black
  - isort
  - pytest
  - pytest-cov
  - hypothesis
  - pdoc
  - pip

category: dev
