channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.8
  - maturin
  - nox
  - mypy
  - ruff
  - Flake8-pyproject
  - flake8-bugbear
  - flake8-pyi
  - black
  - isort
  - pytest
  - coverage
  - hypothesis
  - lark # hypothesis[lark]
  - pip
  - sphinx
  - furo
  - sphinx-copybutton
  - myst-parser
  - pip:
      - sphinx-autoapi
      - sphinx-multiversion

category: dev
