[package]
name = "argus-core"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
itertools = "0.10.5"
paste = "1.0.12"
num-traits = "0.2.15"
thiserror = "1.0.39"

[dev-dependencies]
itertools = "0.10.5"
paste = "1.0.12"
proptest = "1.1.0"
